#!/usr/bin/env python3
# -*- coding: utf-8 -*-

age=20
if age>=18:
    print('your age is',age)
    print('adult')
age=3
if age>=18:
    print('your age is',age)
    print('adult')
else:
    print('your age is',age)
    print('teenager')
age=3
if age>=18:
    print('adult')
elif age>=6:
    print('teenager')
else:
    print('kid')
age=20
if age>=6:
    print('teenager')
elif age>=18:
    print('adult')
else:
    print('kid')
x=3
if x:
    print('True')
birth=input('birth: ')
birth=int(birth)
if birth<2000:
    print('before 2000')
else:
    print('after 2000')

height=1.75
weight=80.5
bmi=weight/(height*height)
if bmi<18.5:
    print('slim')
elif bmi<25:
    print('normal')
elif bmi<28:
    print('overweight')
elif bmi<32:
    print('obesity')
else:
    print('too fat')
print(bmi)
